p8105\_hw3\_cm3928
================
Clement Mugenzi
10/3/2019

``` r
library(p8105.datasets)
data(instacart)
head(instacart)
```

    ## # A tibble: 6 x 15
    ##   order_id product_id add_to_cart_ord… reordered user_id eval_set
    ##      <int>      <int>            <int>     <int>   <int> <chr>   
    ## 1        1      49302                1         1  112108 train   
    ## 2        1      11109                2         1  112108 train   
    ## 3        1      10246                3         0  112108 train   
    ## 4        1      49683                4         0  112108 train   
    ## 5        1      43633                5         1  112108 train   
    ## 6        1      13176                6         0  112108 train   
    ## # … with 9 more variables: order_number <int>, order_dow <int>,
    ## #   order_hour_of_day <int>, days_since_prior_order <int>,
    ## #   product_name <chr>, aisle_id <int>, department_id <int>, aisle <chr>,
    ## #   department <chr>

## A brief description of the dataset

The instacart dataset is comprised of **15** variables and **1384617**
observations.

\*\* I am going to group\_by and summarize character variables.

``` r
doyou = 
  instacart %>% 
  group_by(product_name, department) %>% 
  summarise(n = n())
view(doyou)
```

**How many aisles are there, and which aisles are the most items ordered
from?**

``` r
num_aisle = 
  instacart %>% 
  count(aisle) %>% 
  summarise(n = n())
num_aisle
```

    ## # A tibble: 1 x 1
    ##       n
    ##   <int>
    ## 1   134

``` r
items_ord = 
  instacart %>% 
  group_by(aisle) %>% 
  summarize(n = n()) %>% 
  arrange(-n)
```

``` r
kable(items_ord, markdown)
```

|             aisle             |   n    |
| :---------------------------: | :----: |
|       fresh vegetables        | 150609 |
|         fresh fruits          | 150473 |
|  packaged vegetables fruits   | 78493  |
|            yogurt             | 55240  |
|        packaged cheese        | 41699  |
| water seltzer sparkling water | 36617  |
|             milk              | 32644  |
|        chips pretzels         | 31269  |
|        soy lactosefree        | 26240  |
|             bread             | 23635  |
|         refrigerated          | 23228  |
|         ice cream ice         | 22676  |
|        frozen produce         | 22453  |
|             eggs              | 19875  |
|           crackers            | 19592  |
|         frozen meals          | 18221  |
|      energy granola bars      | 17449  |
|          lunch meat           | 16957  |
|          soft drinks          | 16279  |
|            cereal             | 16201  |
|          fresh herbs          | 16052  |
|     fresh dips tapenades      | 15142  |
|      soup broth bouillon      | 15109  |
|         juice nectars         | 14350  |
|       packaged produce        | 13460  |
|       baby food formula       | 13198  |
|      baking ingredients       | 13088  |
|     other creams cheeses      | 12820  |
|    hot dogs bacon sausage     | 12813  |
|          paper goods          | 12694  |
|   canned jarred vegetables    | 12679  |
|    nuts seeds dried fruit     | 12532  |
|             cream             | 12356  |
|            spreads            | 12102  |
|      canned meals beans       | 11774  |
|        candy chocolate        | 11453  |
|           dry pasta           | 11298  |
|         oils vinegars         | 10620  |
|            butter             | 10575  |
|         cookies cakes         |  9980  |
|         instant foods         |  9917  |
|       breakfast bakery        |  9851  |
|          condiments           |  9743  |
|          pasta sauce          |  9736  |
|       frozen breakfast        |  9729  |
|              tea              |  9376  |
|       spices seasonings       |  9279  |
|    frozen appetizers sides    |  8870  |
|            coffee             |  8392  |
|     tortillas flat bread      |  8353  |
|            missing            |  8251  |
|         frozen pizza          |  7661  |
|          asian foods          |  7007  |
|         popcorn jerky         |  6917  |
|    fruit vegetable snacks     |  6741  |
|   hot cereal pancake mixes    |  6352  |
|    grains rice dried goods    |  6134  |
|       cleaning products       |  5894  |
|       packaged poultry        |  5608  |
|        poultry counter        |  5208  |
|    preserved dips spreads     |  5188  |
|    tofu meat alternatives     |  5123  |
|          buns rolls           |  5054  |
|     pickled goods olives      |  4882  |
|  doughs gelatins bake mixes   |  4758  |
|     energy sports drinks      |  4742  |
|    frozen vegan vegetarian    |  4727  |
|    salad dressing toppings    |  4719  |
|            laundry            |  4636  |
|        prepared meals         |  4133  |
|    canned fruit applesauce    |  3996  |
|       specialty cheeses       |  3873  |
|        dish detergents        |  3870  |
|            granola            |  3803  |
|         latino foods          |  3548  |
|      frozen meat seafood      |  3341  |
|      canned meat seafood      |  3241  |
|         meat counter          |  3159  |
|    breakfast bars pastries    |  3144  |
|         oral hygiene          |  3070  |
|     prepared soups salads     |  2936  |
|         food storage          |  2906  |
|  marinades meat preparation   |  2905  |
|         cat food care         |  2885  |
|     honeys syrups nectars     |  2864  |
|             soap              |  2773  |
|       body lotions soap       |  2137  |
|     vitamins supplements      |  1969  |
|  plates bowls cups flatware   |  1959  |
|         beers coolers         |  1839  |
|             other             |  1795  |
| refrigerated pudding desserts |  1729  |
|          fresh pasta          |  1628  |
|       trash bags liners       |  1621  |
|         dog food care         |  1612  |
|   protein meal replacements   |  1612  |
|     frozen breads doughs      |  1532  |
|         packaged meat         |  1526  |
|        bakery desserts        |  1501  |
|           hair care           |  1469  |
|      trail mix snack mix      |  1463  |
|       cold flu allergy        |  1346  |
|           red wines           |  1243  |
|           digestion           |  1205  |
|         diapers wipes         |  1109  |
|     baking supplies decor     |  1094  |
|          white wines          |  1088  |
|        seafood counter        |  1084  |
|    air fresheners candles     |  1067  |
|       cocoa drink mixes       |  1062  |
|         feminine care         |  1048  |
|            spirits            |  967   |
|           mint gum            |  962   |
|        frozen dessert         |  922   |
|       packaged seafood        |  909   |
|  muscles joints pain relief   |  897   |
|        more household         |  891   |
|          deodorants           |  858   |
|          facial care          |  746   |
| bulk dried fruits vegetables  |  725   |
|         indian foods          |  719   |
| bulk grains rice dried goods  |  634   |
|         kosher foods          |  628   |
|         eye ear care          |  548   |
|           first aid           |  539   |
|           skin care           |  534   |
|          shave needs          |  532   |
|      ice cream toppings       |  504   |
|  specialty wines champagnes   |  461   |
|       kitchen supplies        |  448   |
|      baby bath body care      |  328   |
|       baby accessories        |  306   |
|         frozen juice          |  294   |
|            beauty             |  287   |

There are 134 aisles and fresh vegetables is the most popular aisle with
150609 items ordered from it.

**Make a plot that shows the number of items ordered in each aisle,
limiting this to aisles with more than 10000 items ordered. Arrange
aisles sensibly, and organize your plot so others can read it.**

``` r
plot = 
  items_ord %>%
  filter(n > 10000) %>% 
  ggplot(aes(x = n, y = aisle)) + geom_point()
plot
```

<img src="p8105_hw3_cm3928_files/figure-gfm/unnamed-chunk-6-1.png" width="90%" />
